#!/bin/sh

[[ ! -e /c/aria2.conf ]] && {
  mv aria2.conf /c
}
[[ ! -e /c/aria2.session ]] && {
  touch /c/aria2.session
}

[[ -n $key ]] && {
  sed -i /rpc-secret/s/.*/rpc-secret=$key/ /c/aria2.conf
}

[[ ! -e /c/tracker.sh ]] && {
  mv tracker.sh /c
}

echo '0 3,15 * * * sh /c/tracker.sh' > /var/spool/cron/crontabs/root
crond

exec /aria2c --conf-path=/c/aria2.conf
