services:
  codeserver:
    image: phhb/codeserver
    restart: unless-stopped
    environment:
      - PASSWORD=password
    ports:
      - 0.0.0.0:8081:8081
    volumes:
      - ./home:/root
      - ./data:/data
    command: |
          --disable-update-check
          --disable-telemetry
