services:
  aria2:
    image: phhb/aria2
    restart: unless-stopped
    environment:
      - key=password
    ports:
      - 0.0.0.0:6800:6800
      - 0.0.0.0:6888:6888
      - 0.0.0.0:6888:6888/udp
    volumes:
      - ./data:/c
      - ./d:/d
