#!/bin/sh

[[ ! -d /data/rc.d ]] && {
  mkdir /data/rc.d
}

if [ -n $(ls -A /data/rc.d) ]; then
  for i in /data/rc.d/*.sh; do
    if [ -f $i ]; then
      chmod +x $i
      $i
    fi
  done
fi

exec dumb-init /usr/bin/code-server --user-data-dir /data "$@"
