#!/bin/sh

[[ ! -d /data/rc.d ]] && {
  mkdir /data/rc.d
}

if [ -n $(ls -A /data/rc.d) ]; then
  for i in /data/rc.d/*.sh; do
    if [ -f $i ]; then
      chmod +x $i
      $i
    fi
  done
fi

[[ ! -e /data/flarum/flarum ]] && {
  composer create-project flarum/flarum /data/flarum
  composer clear-cache
}

chown -hR 1000:1000 /init.d /temp /var/log /var/lib/nginx
chown -hR 1000:1000 /data/flarum

exec su-exec 1000:1000 /bin/s6-svscan /init.d
